name: romantic_login_app
description: A romantic Flutter app with phone number login
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl_phone_field: ^3.2.0
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  google_mobile_ads: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
