import '../models/user_profile.dart';

class SampleData {
  static List<UserProfile> get romanticProfiles => [
    UserProfile(
      id: 'user_1',
      name: 'Sarah',
      fullName: 'Sarah Johnson',
      age: 25,
      gender: 'female',
      location: 'New York',
      bio: 'Looking for someone special to share life\'s beautiful moments with 💕',
      image: 'assets/images/profile2.jpeg',
      online: true,
      lastSeen: '2 min ago',
      isVerified: true,
      isSuperLover: true,
      superLoverStatus: 'ready',
      superLoverBio: 'Professional Super Lover with 5+ years experience. Let\'s create magical moments together! ✨',
      superLoverRating: 4.8,
      superLoverCallCount: 127,
    ),
    UserProfile(
      id: 'user_2',
      name: 'Emma',
      fullName: 'Emma Wilson',
      age: 23,
      gender: 'female',
      location: 'Los Angeles',
      bio: 'Adventure seeker with a heart full of love and dreams 🌟',
      image: 'assets/images/profile2.jpeg',
      online: true,
      lastSeen: '5 min ago',
      isVerified: true,
      isSuperLover: true,
      superLoverStatus: 'online',
      superLoverBio: 'Your romantic companion for unforgettable conversations and sweet moments 💖',
      superLoverRating: 4.9,
      superLoverCallCount: 89,
    ),
    UserProfile(
      id: 'user_3',
      name: 'Sophia',
      fullName: 'Sophia Brown',
      age: 27,
      gender: 'female',
      location: 'Chicago',
      bio: 'Passionate about life, love, and creating beautiful memories together 💖',
      image: 'assets/images/profile2.jpeg',
      online: false,
      lastSeen: '1 hour ago',
      isVerified: false,
      isSuperLover: false,
    ),
    UserProfile(
      id: 'user_4',
      name: 'Isabella',
      fullName: 'Isabella Miller',
      age: 24,
      gender: 'female',
      location: 'Miami',
      bio: 'Sunshine and smiles - let\'s make every day feel like a romantic movie 🌅',
      image: 'assets/images/profile2.jpeg',
      online: true,
      lastSeen: 'Just now',
      isVerified: true,
      isSuperLover: true,
      superLoverStatus: 'ready',
      superLoverBio: 'Sunshine Super Lover ready to brighten your day with warm conversations 🌞',
      superLoverRating: 4.7,
      superLoverCallCount: 156,
    ),
    UserProfile(
      id: 'user_5',
      name: 'Olivia',
      fullName: 'Olivia Davis',
      age: 26,
      gender: 'female',
      location: 'Seattle',
      bio: 'Coffee lover with a heart that beats for meaningful connections ☕',
      image: 'assets/images/profile2.jpeg',
      online: false,
      lastSeen: '30 min ago',
      isVerified: false,
      isSuperLover: false,
    ),
    UserProfile(
      id: 'user_6',
      name: 'Ava',
      fullName: 'Ava Garcia',
      age: 22,
      gender: 'female',
      location: 'Boston',
      bio: 'Dreamer with a passion for love stories and romantic adventures 💫',
      image: 'assets/images/profile2.jpeg',
      online: true,
      lastSeen: '10 min ago',
      isVerified: true,
      isSuperLover: true,
      superLoverStatus: 'online',
      superLoverBio: 'Dreamy Super Lover who believes in the magic of love and connection ✨',
      superLoverRating: 4.6,
      superLoverCallCount: 73,
    ),
    UserProfile(
      id: 'user_7',
      name: 'Mia',
      fullName: 'Mia Rodriguez',
      age: 24,
      gender: 'female',
      location: 'San Francisco',
      bio: 'Tech enthusiast who believes in the magic of love and connection ✨',
      image: 'assets/images/profile2.jpeg',
      online: true,
      lastSeen: 'Just now',
      isVerified: false,
      isSuperLover: false,
    ),
    UserProfile(
      id: 'user_8',
      name: 'Luna',
      fullName: 'Luna Martinez',
      age: 23,
      gender: 'female',
      location: 'Austin',
      bio: 'Music lover seeking harmony in love and life 🎵',
      image: 'assets/images/profile2.jpeg',
      online: false,
      lastSeen: '45 min ago',
      isVerified: true,
      isSuperLover: true,
      superLoverStatus: 'offline',
      superLoverBio: 'Musical Super Lover who creates harmony in every conversation 🎶',
      superLoverRating: 4.5,
      superLoverCallCount: 42,
    ),
    UserProfile(
      id: 'user_9',
      name: 'Zoe',
      fullName: 'Zoe Anderson',
      age: 25,
      gender: 'female',
      location: 'Denver',
      bio: 'Nature lover who finds beauty in every moment 🌿',
      image: 'assets/images/profile2.jpeg',
      online: true,
      lastSeen: '3 min ago',
      isVerified: false,
      isSuperLover: false,
    ),
    UserProfile(
      id: 'user_10',
      name: 'Chloe',
      fullName: 'Chloe Taylor',
      age: 26,
      gender: 'female',
      location: 'Portland',
      bio: 'Creative soul looking for someone to share artistic adventures with 🎨',
      image: 'assets/images/profile2.jpeg',
      online: true,
      lastSeen: 'Just now',
      isVerified: true,
      isSuperLover: true,
      superLoverStatus: 'ready',
      superLoverBio: 'Creative Super Lover who paints beautiful conversations with words 🎨',
      superLoverRating: 4.8,
      superLoverCallCount: 98,
    ),
  ];
}
